---
title: "Clustering"
output: html_notebook
---

```{r setup and import data}

library(tidyverse)
library(tibble)
library(lubridate)
library(GGally)
library(cluster)
library(VIM)
library(fpc)
library(tidyr)
library(dplyr)
library(knitr)
library(ggplot2)
library(rio)
library(factoextra)
library(FactoMineR)

import <- read_csv("inst/edited_spotify.csv")

```

```{r clean and split data}

spotify <- import %>%
  mutate(AlbumReleaseDate = parse_date_time(AlbumReleaseDate, orders = c("y", "ym","ymd"))) %>%
  #Old-school grepl method
  mutate(Artist = ifelse(grepl("Beyonc*", Artist), 'Beyonce', Artist)) %>%
  #Tidyverse str_detect method
  mutate(Artist = ifelse(Artist %>% 
                           str_detect("Janelle Mon*"), 'Janelle Monae', Artist)) %>%
  mutate(AlbumBestChartPosition = ifelse(AlbumBestChartPosition %>% 
                           str_detect("#N/A"), 0, AlbumBestChartPosition)) %>%
  na.omit() %>%
  mutate(id = row_number()) %>%
  mutate(id = as.character(id))
sapply(data, class)

test_data <- subset(spotify, ((AlbumName == "A Girl Called Dusty") | 
                                 (AlbumName == "Action!") |
                                 (AlbumName == "Selling England By The Pound") |
                                 (AlbumName == "Carpenters") | 
                                 (AlbumName == "Ride On") |
                                 (AlbumName == "Autoamerican") |
                                 (AlbumName == "Selected Ambient Works 85-92") |    
                                 (AlbumName == "Different Class") |
                                 (AlbumName == "O") |
                                 (AlbumName == "The Elder Scrolls IV: Oblivion: Original Game Soundtrack") |
                                 (AlbumName == "AM") |
                                 (AlbumName == "An Awesome Wave")))

training_data <- subset(spotify, ((AlbumName != "A Girl Called Dusty") & 
                                     (AlbumName != "Action!") &
                                     (AlbumName != "Selling England By The Pound") &
                                     (AlbumName != "Carpenters") & 
                                     (AlbumName != "Ride On") &
                                     (AlbumName != "Autoamerican") &
                                     (AlbumName != "Selected Ambient Works 85-92") &    
                                     (AlbumName != "Different Class") &
                                     (AlbumName != "O") &
                                     (AlbumName != "The Elder Scrolls IV: Oblivion: Original Game Soundtrack") &
                                     (AlbumName != "AM") &
                                     (AlbumName != "An Awesome Wave")))

```

```{r find genres}

genres <- mutate(training_data, ArtistGenres = strsplit(ArtistGenres, ","))$ArtistGenres %>% 
  unlist() %>% unique() %>% na.omit()

split_genres <- NULL

for(i in 1:length(genres)) {
  split_genres[i] <- strsplit(genres[i], " ")
}

genre_words <- unlist(split_genres)

#genre_words <- replace(genre_words, (genre_words == "hip" | genre_words == "hop"), "hip-hop")

unique_genre_words <- unique(genre_words)

cutoff_freq <- 5

most_frequent_words <- subset(as.data.frame(table(genre_words)), (Freq > cutoff_freq))

genre_freq_plot <- most_frequent_words %>% 
  ggplot(aes(x=genre_words, y=Freq)) + geom_col()

print(genre_freq_plot)

```

```{r genre overlap function}

genre_overlap <- function(genre1, genre2) {
  
  genre_appearance <- 0
  overlap <- 0
  
  for(i in 1:length(training_data$Artist)){
    
    if(str_detect(training_data$ArtistGenres[i], genre1) &
       str_detect(training_data$ArtistGenres[i], genre2)) {
      
       overlap <- overlap + 1
       genre_appearance <- genre_appearance + 1
    
    } else {
      
      if(str_detect(training_data$ArtistGenres[i], genre2)){
      genre_appearance <- genre_appearance + 1
      }
      
      if(str_detect(training_data$ArtistGenres[i], genre1)){
      genre_appearance <- genre_appearance + 1
      }
    }
  }
  
  return(overlap/(genre_appearance))
}

```

```{r find genre overlaps}

genre_overlaps <- matrix(nrow = length(most_frequent_words$genre_words),
                         ncol = length(most_frequent_words$genre_words),
                         dimnames = list(as.character(most_frequent_words$genre_words),
                                         as.character(most_frequent_words$genre_words)))

for(i in 1:length(most_frequent_words$genre_words)) {
  for(j in 1:length(most_frequent_words$genre_words)) {
    genre_overlaps[i,j] <- genre_overlap(as.character(most_frequent_words$genre_words[i]),
                                         as.character(most_frequent_words$genre_words[j]))
  }
}

most_frequent_words %>% mutate(correlationcoeff = colSums(genre_overlaps))

```

```{r link genres to tracks}

# associate tracks that have multiple genres with the most frequent genre (since these will be broader)

training_data <- training_data %>% mutate(TrueCluster = (row_number()-row_number()))

for(i in 1:length(training_data$ArtistID)) {
  if(str_detect(training_data$ArtistGenres[i], "folk")) {training_data$TrueCluster[i] <- 5}
  if(str_detect(training_data$ArtistGenres[i], "indie")) {training_data$TrueCluster[i] <- 4}
  if(str_detect(training_data$ArtistGenres[i], "hip")) {training_data$TrueCluster[i] <- 3}
  if(str_detect(training_data$ArtistGenres[i], "hop")) {training_data$TrueCluster[i] <- 3}
  if(str_detect(training_data$ArtistGenres[i], "pop")) {training_data$TrueCluster[i] <- 2}
  if(str_detect(training_data$ArtistGenres[i], "rock")) {training_data$TrueCluster[i] <- 1}
}

```

```{r clustering}

clustering_training_data <- training_data[c("TrackDuration", "TrackDanceability",
                                            "TrackEnergy", "TrackKey", "TrackLoudness",
                                            "TrackSpeechiness", "TrackAcousticness",
                                            "TrackInstrumentalness", "TrackLiveness", 
                                            "TrackValence", "TrackTempo")]

clusters <- pam(clustering_training_data, 6)

plotcluster(clustering_training_data, clusters$cluster)

```














