---
title: "tut"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r genre overlap function}

genre_overlap <- function(genre1, genre2) {
  
  genre_appearance <- 0
  overlap <- 0
  
  for(i in 1:length(training_data$Artist)){
    
    if(str_detect(training_data$ArtistGenres[i], genre1) &
       str_detect(training_data$ArtistGenres[i], genre2)) {
      
       overlap <- overlap + 1
       genre_appearance <- genre_appearance + 1
    
    } else {
      
      if(str_detect(training_data$ArtistGenres[i], genre2)){
      genre_appearance <- genre_appearance + 1
      }
      
      if(str_detect(training_data$ArtistGenres[i], genre1)){
      genre_appearance <- genre_appearance + 1
      }
    }
  }
  
  return(overlap/(genre_appearance))
}

```

```{r find genre overlaps}

genre_overlaps <- matrix(nrow = length(most_frequent_words$genre_words),
                         ncol = length(most_frequent_words$genre_words),
                         dimnames = list(as.character(most_frequent_words$genre_words),
                                         as.character(most_frequent_words$genre_words)))

for(i in 1:length(most_frequent_words$genre_words)) {
  for(j in 1:length(most_frequent_words$genre_words)) {
    genre_overlaps[i,j] <- genre_overlap(as.character(most_frequent_words$genre_words[i]),
                                         as.character(most_frequent_words$genre_words[j]))
  }
}

most_frequent_words <- most_frequent_words %>% mutate(correlationcoeff = colSums(genre_overlaps))
most_frequent_words <- most_frequent_words %>% mutate(wbcf = Freq/correlationcoeff)

plot2 <- ggplot(data=most_frequent_words, aes(x=wbcf, y=Freq)) + geom_point()+theme_dark()


```

```{r link genres to tracks}

# associate tracks that have multiple genres with the most frequent genre (since these will be broader)

training_data <- training_data %>% mutate(TrueCluster = (row_number()-row_number()))

for(i in 1:length(training_data$ArtistID)) {
  if(str_detect(training_data$ArtistGenres[i], "folk")) {training_data$TrueCluster[i] <- 5}
  if(str_detect(training_data$ArtistGenres[i], "indie")) {training_data$TrueCluster[i] <- 4}
  if(str_detect(training_data$ArtistGenres[i], "hip")) {training_data$TrueCluster[i] <- 3}
  if(str_detect(training_data$ArtistGenres[i], "hop")) {training_data$TrueCluster[i] <- 3}
  if(str_detect(training_data$ArtistGenres[i], "pop")) {training_data$TrueCluster[i] <- 2}
  if(str_detect(training_data$ArtistGenres[i], "rock")) {training_data$TrueCluster[i] <- 1}
}

```