---
title: "Task_1"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries}
library(tidyverse)
library(lubridate)
library(GGally)
library(cluster)
library(VIM)
library(fpc)
library(leaps)
library(readxl)
library(corrplot)
library(ggvis)
```


```{r code setup}
spotify.clustering <- read_excel("edited_spotify.xlsx")

clean_data <- spotify.clustering %>%
  mutate(AlbumReleaseDate = parse_date_time(AlbumReleaseDate, orders = c("y", "ym","ymd"))) %>%
  #Old-school grepl method
  mutate(Artist = ifelse(grepl("Beyonc*", Artist), 'Beyonce', Artist)) %>%
  #Tidyverse str_detect method
  mutate(Artist = ifelse(Artist %>% 
                           str_detect("Janelle Mon*"), 'Janelle Monae', Artist)) %>%
  mutate(AlbumBestChartPosition = ifelse(AlbumBestChartPosition %>% 
                           str_detect("#N/A"), 0, AlbumBestChartPosition)) %>%
  na.omit() %>%
  mutate(id = row_number()) %>%
  mutate(id = as.character(id))


aggr(clean_data) # checks for missing data

test_data <- subset(clean_data, ((AlbumName == "A Girl Called Dusty") | 
                                 (AlbumName == "Action!") |
                                 (AlbumName == "Selling England By The Pound") |
                                 (AlbumName == "Carpenters") | 
                                 (AlbumName == "Ride On") |
                                 (AlbumName == "Autoamerican") |
                                 (AlbumName == "Selected Ambient Works 85-92") |    
                                 (AlbumName == "Different Class") |
                                 (AlbumName == "O") |
                                 (AlbumName == "The Elder Scrolls IV: Oblivion: Original Game Soundtrack") |
                                 (AlbumName == "AM") |
                                 (AlbumName == "An Awesome Wave")))

training_data <- subset(clean_data, ((AlbumName != "A Girl Called Dusty") & 
                                     (AlbumName != "Action!") &
                                     (AlbumName != "Selling England By The Pound") &
                                     (AlbumName != "Carpenters") & 
                                     (AlbumName != "Ride On") &
                                     (AlbumName != "Autoamerican") &
                                     (AlbumName != "Selected Ambient Works 85-92") &    
                                     (AlbumName != "Different Class") &
                                     (AlbumName != "O") &
                                     (AlbumName != "The Elder Scrolls IV: Oblivion: Original Game Soundtrack") &
                                     (AlbumName != "AM") &
                                     (AlbumName != "An Awesome Wave")))

training_data_subsetted <- training_data[c("TrackDuration", "TrackDanceability",
                                 "TrackEnergy", "TrackKey", "TrackLoudness",
                                 "TrackSpeechiness", "TrackAcousticness",
                                 "TrackInstrumentalness", "TrackLiveness", "TrackValence",
                                 "TrackTempo")]
```


## General EDA

```{r summarisies}
MyData = {training_data %>% 
    group_by(Artist,AlbumName,AlbumPopularity) %>% 
    summarize(AlbumDanceability = mean(TrackDanceability),
              AlbumLoudness = mean(TrackLoudness),
              AlbumSpeechiness = mean(TrackSpeechiness),
              AlbumDuration = mean(TrackDuration),
              AlbumNumber = mean(TrackNumber),	
              AlbumEnergy = mean(TrackEnergy),	
              AlbumKey = mean(TrackKey),	
              AlbumMode = mean(TrackMode),	
              AlbumAcousticness = mean(TrackAcousticness),	
              AlbumInstrumentalness = mean(TrackInstrumentalness),	
              AlbumLiveness = mean(TrackLiveness),
              AlbumValence = mean(TrackValence),
              AlbumTempo = mean(TrackTempo),	
              AlbumTimeSignature = mean(TrackTimeSignature) )}


#group by AlbumName
MyData3 = {training_data %>% 
    group_by(AlbumName) %>% 
    summarize(
      
      AlbumBestChartPosition = mean(AlbumBestChartPosition),
      AlbumWeeksOnChart = mean( AlbumWeeksOnChart),
       AlbumWeeksNumberOne = mean(AlbumWeeksNumberOne),
       AlbumPopularity = mean(AlbumPopularity),
        AlbumReleaseDate = AlbumReleaseDate[1],
         AlbumDanceability = mean(TrackDanceability),
              AlbumLoudness = mean(TrackLoudness),
              AlbumSpeechiness = mean(TrackSpeechiness),
              AlbumDuration = mean(TrackDuration),
              AlbumNumber = mean(TrackNumber),	
              AlbumEnergy = mean(TrackEnergy),	
              AlbumKey = mean(TrackKey),	
              AlbumMode = mean(TrackMode),	
              AlbumAcousticness = mean(TrackAcousticness),	
              AlbumInstrumentalness = mean(TrackInstrumentalness),	
              AlbumLiveness = mean(TrackLiveness),
              AlbumValence = mean(TrackValence),
              AlbumTempo = mean(TrackTempo),	
              AlbumTimeSignature = mean(TrackTimeSignature) )}










#the mean method

MyData1 = {training_data %>% 
    group_by(ArtistPopularity) %>% 
    summarize(ArtistDanceability = mean(TrackDanceability),
              ArtistLoudness = mean(TrackLoudness),
              ArtistSpeechiness = mean(TrackSpeechiness),
              ArtistDuration = mean(TrackDuration),
              ArtistNumber = mean(TrackNumber),	
              ArtistEnergy = mean(TrackEnergy),	
              ArtistKey = mean(TrackKey),	
              ArtistMode = mean(TrackMode),	
              ArtistAcousticness = mean(TrackAcousticness),	
              ArtistInstrumentalness = mean(TrackInstrumentalness),	
              ArtistLiveness = mean(TrackLiveness),
              ArtistValence = mean(TrackValence),
              ArtistTempo = mean(TrackTempo),	
              ArtistTimeSignature = mean(TrackTimeSignature) )}


```

## Specific Task 1 EDA

```{r album popularity}
MyData2 = {training_data %>% 
    group_by(AlbumPopularity) %>% 
    summarize(AlbumDanceability = mean(TrackDanceability),
              AlbumLoudness = mean(TrackLoudness),
              AlbumSpeechiness = mean(TrackSpeechiness),
              AlbumDuration = mean(TrackDuration),
              AlbumNumber = mean(TrackNumber),	
              AlbumEnergy = mean(TrackEnergy),	
              AlbumKey = mean(TrackKey),	
              AlbumMode = mean(TrackMode),	
              AlbumAcousticness = mean(TrackAcousticness),	
              AlbumInstrumentalness = mean(TrackInstrumentalness),	
              AlbumLiveness = mean(TrackLiveness),
              AlbumValence = mean(TrackValence),
              AlbumTempo = mean(TrackTempo),	
              AlbumTimeSignature = mean(TrackTimeSignature) )}

ggpairs(MyData2)

MyData2 %>% ggplot(aes(x =AlbumDanceability,y = AlbumPopularity)) + geom_point()  + geom_smooth()

MyData2 %>% ggplot(aes(x = AlbumLoudness,y = AlbumPopularity)) + geom_point()  + geom_smooth()

MyData2 %>% ggplot(aes(x =  AlbumEnergy ,y = AlbumPopularity)) + geom_point()  + geom_smooth()

MyData2 %>% ggplot(aes(x =  AlbumTimeSignature   ,y = AlbumPopularity)) + geom_point()  + geom_smooth()


res <- strsplit(training_data$ArtistGenres, split = ",")
uniques <- unique(unlist(res))

res2 <- NULL
for(i in 1:nrow(training_data)) {
  temp <- match(uniques, res[[i]])
  res2 <- rbind(res2, temp)
}

res2[is.na(res2)] <- 0
res2[res2 > 0] <- 1
colnames(res2) <- uniques
row.names(res2) <- 1:nrow(res2)
newdat <- data.frame(year = year(training_data$AlbumReleaseDate), 
                     popularity = training_data$ArtistPopularity,
                     res2)
means2 <- c()
for(i in 3:ncol(newdat)) {
    
    means <- aggregate(popularity ~ year ,data = newdat[newdat[,i]==1,], mean)
    means$type <- colnames(newdat)[i]
    means2 <- rbind(means2, means)
}

means21 <-   NULL
  
  for(i in sort( unique(means2$year))) {
    
  aa <- means2[ means2$year == i,]
  
  pos <- which.max(aa$popularity)
    
   means21 <-  rbind(means21 , c(i,aa$popularity[pos], aa$type[pos]))
  }

means21 = data.frame(means21)
colnames(means21) <- c("year","popularity","type")
means21$year <- as.integer(as.character(means21$year))
means21$popularity <- as.numeric(as.character(means21$popularity))

ggplot(means21, aes(year, popularity)) + geom_line(color = "indianred") + geom_point(color = "blue") + 
  theme_classic() + geom_text(aes(label = type),  size = 4, nudge_y = 0.1) + ggtitle("all time most popularity music type")



```


```{r}
correlations <- round(cor(training_data_subsetted),2)
correlations

col <- colorRampPalette(c("#BB4444", "#EE9988", "#FFFFFF", "#77AADD", "#4477AA"))
p.mat <- cor.mtest(training_data_subsetted)$p
corrplot(correlations, method = "color", col = col(200),
         type = "upper", order = "hclust",
         tl.col = "black", tl.srt = 90, # Text label color and rotation
         addCoef.col = "black",
         # Combine with significance
         p.mat = p.mat, sig.level = 0.01, insig = "blank", 
         # hide correlation coefficient on the principal diagonal
         diag = FALSE, tl.cex = 0.8)
```

A new popularity variable needs to be defined to take into account all the other popularity variables


```{r newPop, warnings = FALSE}
#Looking at implementing new variables for each popularity variable
#Can then take this and normalise to give a score out of 100.
#To start with the whole training dataset will be used
normy <- function(x){
  x <- as.numeric(x)
  quantile(x, c(0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1), na.rm = TRUE)
}
#Assumption: NA means it didn't reach the charts, lower the position the better
abcp_normy <- normy(training_data$AlbumBestChartPosition)
anf_normy <- normy(training_data$ArtistNumFollowers)
awoc_normy <- normy(training_data$AlbumWeeksOnChart)
awn1_normy <- normy(training_data$AlbumWeeksNumberOne)
ap_normy <- normy(training_data$AlbumPopularity)
artp_normy <- normy(training_data$ArtistPopularity)

#Gets the 20% percentile for example
as.numeric(abcp_normy[6])

training_data <- training_data %>%
  mutate(album_bcp = if_else(AlbumBestChartPosition == 0, 1,
                         if_else(AlbumBestChartPosition == 1, 10,
                         if_else(AlbumBestChartPosition == 2, 9,
                         if_else(AlbumBestChartPosition == 3, 8,
                           0 ))))) %>% #... repeat for other variables
  mutate(artist_follow_n = 0) %>%
  mutate(album_pop_n = 0) %>%
  mutate(artist_pop_n = 0) %>%
  mutate(album_weeks_on_chart_n = if_else(AlbumWeeksOnChart == 0, 1, 0)) %>%
  mutate(album_weeks_number_1n = if_else(AlbumWeeksNumberOne == 0, 1, 0)) %>%
  mutate(popularity = -1)

# training_data <- training_data %>%
#   mutate(album_bcp = 0) %>%
#   mutate(artist_follow_n = 0) %>%
#   mutate(album_pop_n = 0) %>%
#   mutate(artist_pop_n = 0) %>%
#   mutate(album_weeks_on_chart_n = 0) %>%
#   mutate(album_weeks_number_1n = 0)

#album weeks number 1, this is fine as we are going > 0 and =< 1
for(i in 8:10){
  for(j in 1:nrow(training_data)){
      if(training_data$AlbumWeeksNumberOne[j] > as.numeric(awn1_normy[i]) &&
         training_data$AlbumWeeksNumberOne[j] <= as.numeric(awn1_normy[i + 1])){
    training_data$album_weeks_number_1n[j] = i
  }
  }
}

for(i in 2:10){
  for(j in 1:nrow(training_data)){
      if(training_data$AlbumWeeksOnChart[j] > as.numeric(awoc_normy[i]) &&
         training_data$AlbumWeeksOnChart[j] <= as.numeric(awoc_normy[i + 1])){
    training_data$album_weeks_on_chart_n[j] = i
  }
  }
}

#album weeks on chart

#albumchartposition
for(i in 6:10){
  for(j in 1:nrow(training_data)){
      if(training_data$AlbumBestChartPosition[j] > as.numeric(abcp_normy[i]) &&
         training_data$AlbumBestChartPosition[j] <= as.numeric(abcp_normy[i + 1])){
    training_data$album_bcp[j] = (12-i)
  }
  }
}

#This is obviously wrong but not sure why... Looks like it should be working to me        
#Updating artist_followers, need to sort it for end case, last one needs to be <= not <0
# Can probably just mutate into it tbh at the end to fix all last cases.
for(i in 1:10){
  for(j in 1:nrow(training_data)){
      if(training_data$ArtistNumFollowers[j] >= as.numeric(anf_normy[i]) &&
         training_data$ArtistNumFollowers[j] < as.numeric(anf_normy[i + 1])){
    training_data$artist_follow_n[j] = i
  }
  }
}
#Create and update artist_popularity
for(i in 1:10){
  for(j in 1:nrow(training_data)){
      if(training_data$ArtistPopularity[j] >= as.numeric(artp_normy[i]) &&
         training_data$ArtistPopularity[j] < as.numeric(artp_normy[i + 1])){
    training_data$artist_pop_n[j] = i
  }
  }
}
#Create and update album popularity
for(i in 1:10){
  for(j in 1:nrow(training_data)){
      if(training_data$AlbumPopularity[j] >= as.numeric(ap_normy[i]) &&
         training_data$AlbumPopularity[j] < as.numeric(ap_normy[i + 1])){
    training_data$album_pop_n[j] = i
  }
  }
}
#Could maybe add a years from release as a penalty to make newer songs higher rated or subset the data?
#Should probably add some sort of verification to the numbers for now they are arbitrary?
training_data_pop <- training_data %>%
  mutate(popularity = ((25 * training_data$album_pop_n + 25 * training_data$artist_pop_n +
                         25 * training_data$artist_follow_n + 10 * training_data$album_bcp +
                         10 * training_data$album_weeks_on_chart_n +
                         5 * training_data$album_weeks_number_1n)/10))


bar_plot <- function(x){
  training_data %>% 
  ggplot(aes_string(x = x)) + 
  geom_bar() +
    theme_bw() +
    scale_x_discrete(limits = c(0,2,4,6,8,10))
}
lapply(c("artist_follow_n", "artist_pop_n","album_pop_n","album_bcp",
         "album_weeks_on_chart_n", "album_weeks_number_1n"), bar_plot)
```


```{r leaps}
#all subsets regression

tr <- training_data[,-c(1,2,3,6,7,12, 13,14,29)]

m <- regsubsets(ArtistPopularity ~ ., data = tr,
                method = "backward")

summary(m)

#measures
par(mfrow = c(1,1))

plot(m, scale = "Cp")

plot(m, scale = "bic")

plot(m, scale = "adjr2")


#check Adjusted R2
rsq <- as.data.frame(summary(m)$adjr2)
names(rsq) <- "Adjusted-R2"
rsq %>% 
        ggvis(x=~ c(1:nrow(rsq)), y=~`Adjusted-R2` ) %>%
        layer_points(fill = ~`Adjusted-R2`) %>%
        add_axis("y", title = "Adjusted-R2`") %>% 
        add_axis("x", title = "Number of variables")

#the final Adjusted R2 is very high

reg.summary <- summary(m)


#compare RSS, Cp, bic, adjr2
par(mfrow=c(2,2))
plot(reg.summary$rss ,xlab="Number of Variables ",ylab="RSS",type="l")
plot(reg.summary$adjr2 ,xlab="Number of Variables ", ylab="Adjusted RSq",type="l")
which.max(reg.summary$adjr2)
points(which.max(reg.summary$adjr2),reg.summary$adjr2[which.max(reg.summary$adjr2)], col="red",cex=2,pch=20)
plot(reg.summary$cp ,xlab="Number of Variables ",ylab="Cp", type='l')
which.min(reg.summary$cp )
points(which.min(reg.summary$cp ),reg.summary$cp [which.min(reg.summary$cp )],col="red",cex=2,pch=20)
plot(reg.summary$bic ,xlab="Number of Variables ",ylab="BIC",type='l')
which.min(reg.summary$bic )
points(which.min(reg.summary$bic ),reg.summary$bic [which.min(reg.summary$bic )],col="red",cex=2,pch=20)
par(mfrow=c(1,1))


coef(m, 8)


#a selected best model by adjr2, Cp, bic
m1 <- lm(ArtistPopularity ~ ArtistNumFollowers  +  AlbumPopularity  +  TrackEnergy  +    TrackLoudness + album_bcp + artist_follow_n +  album_pop_n + artist_pop_n ,data=tr)
summary(m1)


```

```{r}
#form testing data
#Assumption: NA means it didn't reach the charts, lower the position the better
abcp_normy <- normy(test_data$AlbumBestChartPosition)
anf_normy <- normy(test_data$ArtistNumFollowers)
awoc_normy <- normy(test_data$AlbumWeeksOnChart)
awn1_normy <- normy(test_data$AlbumWeeksNumberOne)
ap_normy <- normy(test_data$AlbumPopularity)
artp_normy <- normy(test_data$ArtistPopularity)

#Gets the 20% percentile for example
as.numeric(abcp_normy[6])

test_data <- test_data %>%
  mutate(album_bcp = if_else(AlbumBestChartPosition == 0, 1,
                             if_else(AlbumBestChartPosition == 1, 10,
                                     if_else(AlbumBestChartPosition == 2, 9,
                                             if_else(AlbumBestChartPosition == 3, 8,
                                                     0 ))))) %>% #... repeat for other variables
  mutate(artist_follow_n = 0) %>%
  mutate(album_pop_n = 0) %>%
  mutate(artist_pop_n = 0) %>%
  mutate(album_weeks_on_chart_n = if_else(AlbumWeeksOnChart == 0, 1, 0)) %>%
  mutate(album_weeks_number_1n = if_else(AlbumWeeksNumberOne == 0, 1, 0)) %>%
  mutate(popularity = -1)

# test_data <- test_data %>%
#   mutate(album_bcp = 0) %>%
#   mutate(artist_follow_n = 0) %>%
#   mutate(album_pop_n = 0) %>%
#   mutate(artist_pop_n = 0) %>%
#   mutate(album_weeks_on_chart_n = 0) %>%
#   mutate(album_weeks_number_1n = 0)

#album weeks number 1, this is fine as we are going > 0 and =< 1
for(i in 8:10){
  for(j in 1:nrow(test_data)){
    if(test_data$AlbumWeeksNumberOne[j] > as.numeric(awn1_normy[i]) &&
       test_data$AlbumWeeksNumberOne[j] <= as.numeric(awn1_normy[i + 1])){
      test_data$album_weeks_number_1n[j] = i
    }
  }
}

for(i in 2:10){
  for(j in 1:nrow(test_data)){
    if(test_data$AlbumWeeksOnChart[j] > as.numeric(awoc_normy[i]) &&
       test_data$AlbumWeeksOnChart[j] <= as.numeric(awoc_normy[i + 1])){
      test_data$album_weeks_on_chart_n[j] = i
    }
  }
}

#album weeks on chart

#albumchartposition
for(i in 6:10){
  for(j in 1:nrow(test_data)){
    if(test_data$AlbumBestChartPosition[j] > as.numeric(abcp_normy[i]) &&
       test_data$AlbumBestChartPosition[j] <= as.numeric(abcp_normy[i + 1])){
      test_data$album_bcp[j] = (12-i)
    }
  }
}

#This is obviously wrong but not sure why... Looks like it should be working to me        
#Updating artist_followers, need to sort it for end case, last one needs to be <= not <0
# Can probably just mutate into it tbh at the end to fix all last cases.
for(i in 1:10){
  for(j in 1:nrow(test_data)){
    if(test_data$ArtistNumFollowers[j] >= as.numeric(anf_normy[i]) &&
       test_data$ArtistNumFollowers[j] < as.numeric(anf_normy[i + 1])){
      test_data$artist_follow_n[j] = i
    }
  }
}
#Create and update artist_popularity
for(i in 1:10){
  for(j in 1:nrow(test_data)){
    if(test_data$ArtistPopularity[j] >= as.numeric(artp_normy[i]) &&
       test_data$ArtistPopularity[j] < as.numeric(artp_normy[i + 1])){
      test_data$artist_pop_n[j] = i
    }
  }
}
#Create and update album popularity
for(i in 1:10){
  for(j in 1:nrow(test_data)){
    if(test_data$AlbumPopularity[j] >= as.numeric(ap_normy[i]) &&
       test_data$AlbumPopularity[j] < as.numeric(ap_normy[i + 1])){
      test_data$album_pop_n[j] = i
    }
  }
}
#Could maybe add a years from release as a penalty to make newer songs higher rated or subset the data?
#Should probably add some sort of verification to the numbers for now they are arbitrary?
test_data_pop <- test_data %>%
  mutate(popularity = ((25 * test_data$album_pop_n + 25 * test_data$artist_pop_n +
                          25 * test_data$artist_follow_n + 10 * test_data$album_bcp +
                          10 * test_data$album_weeks_on_chart_n +
                          5 * test_data$album_weeks_number_1n)/10))

```



```{r}
#predictions on testing data
preds <- predict(m1, newdata = test_data )

rmse <- sqrt( mean((preds - test_data$ArtistPopularity)^2) )

rmse
```




